server:
  port: 9090
# DataSource Driver
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
  mvc:
    static-path-pattern: /resources/**