server:
  port: 9090

spring:
  # DataSource Driver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf8
    username: root
    password: root
  # view templates
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
  #  static Resource visited path
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .html1
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

