server:
  port: 9090
  servlet:
    context-path: /sys
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  # DataSource Driver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf8
    username: root
    password: root
  # view templates
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: HTML
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: static/**
  resource:
    static-locations: classpath:/static/,classpath:/public/


