server:
  port: 9090

spring:
  # DataSource Driver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf8
    username: root
    password: root
  # view templates
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html


